# Generated by Django 4.2.5 on 2023-09-07 04:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('pic', models.ImageField(upload_to='media/')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('country', models.CharField(default='', max_length=25)),
                ('is_dead', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('image', models.ImageField(upload_to='book/')),
                ('price', models.FloatField(default=0)),
                ('pages', models.PositiveSmallIntegerField(default=5)),
                ('year', models.PositiveSmallIntegerField(default=1900)),
                ('desc', models.TextField(default='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='add_book.authormodel')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='add_book.genermodel')),
            ],
        ),
        migrations.AddField(
            model_name='authormodel',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_book.genermodel'),
        ),
    ]
